# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-19 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='last_namen',
            new_name='last_name',
        ),
    ]
